-- Generated by VibeDB

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR NOT NULL UNIQUE,
  username VARCHAR NOT NULL UNIQUE,
  display_name VARCHAR NOT NULL,
  avatar_url TEXT,
  bio TEXT,
  timezone VARCHAR NOT NULL DEFAULT 'UTC',
  locale VARCHAR NOT NULL DEFAULT 'en',
  global_profile JSONB DEFAULT '{}',
  is_bot BOOLEAN NOT NULL DEFAULT false,
  is_verified BOOLEAN NOT NULL DEFAULT false,
  last_seen_at TIMESTAMP,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE workspaces (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR NOT NULL,
  slug VARCHAR NOT NULL UNIQUE,
  plan VARCHAR NOT NULL DEFAULT 'free',
  owner_id UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  logo_url TEXT,
  settings JSONB DEFAULT '{}',
  is_active BOOLEAN NOT NULL DEFAULT true,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE user_credentials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  password_hash TEXT NOT NULL,
  reset_token VARCHAR,
  reset_token_expires_at TIMESTAMP,
  reset_token_last_rotated_at TIMESTAMP,
  mfa_secret VARCHAR,
  mfa_enabled BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE user_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  session_token VARCHAR NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  last_rotated_at TIMESTAMP NOT NULL DEFAULT now(),
  ip_address VARCHAR,
  user_agent TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE workspace_memberships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  role VARCHAR NOT NULL DEFAULT 'member',
  status VARCHAR NOT NULL DEFAULT 'active',
  invited_by UUID REFERENCES users(id) ON DELETE RESTRICT,
  profile_override JSONB DEFAULT '{}',
  notification_preferences JSONB DEFAULT '{}',
  joined_at TIMESTAMP,
  deactivated_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE workspace_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  name VARCHAR NOT NULL,
  description TEXT,
  permissions JSONB NOT NULL DEFAULT '[]',
  is_system BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE SET NULL,
  type VARCHAR NOT NULL,
  name VARCHAR,
  slug VARCHAR,
  topic TEXT,
  description TEXT,
  is_private BOOLEAN NOT NULL DEFAULT false,
  is_archived BOOLEAN NOT NULL DEFAULT false,
  is_read_only BOOLEAN NOT NULL DEFAULT false,
  created_by UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  last_message_at TIMESTAMP,
  message_count INT NOT NULL DEFAULT 0,
  settings JSONB DEFAULT '{}',
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE SET NULL,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE SET NULL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  parent_message_id UUID REFERENCES messages(id) ON DELETE SET NULL,
  thread_root_id UUID REFERENCES messages(id) ON DELETE SET NULL,
  content TEXT,
  content_format VARCHAR NOT NULL DEFAULT 'markdown',
  type VARCHAR NOT NULL DEFAULT 'text',
  subtype VARCHAR,
  is_edited BOOLEAN NOT NULL DEFAULT false,
  edited_at TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_at TIMESTAMP,
  is_pinned BOOLEAN NOT NULL DEFAULT false,
  is_ephemeral BOOLEAN NOT NULL DEFAULT false,
  reply_count INT NOT NULL DEFAULT 0,
  reaction_count INT NOT NULL DEFAULT 0,
  metadata JSONB DEFAULT '{}',
  blocks JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE conversation_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  role VARCHAR NOT NULL DEFAULT 'member',
  last_read_at TIMESTAMP,
  last_read_message_id UUID REFERENCES messages(id) ON DELETE RESTRICT,
  notification_level VARCHAR NOT NULL DEFAULT 'default',
  is_muted BOOLEAN NOT NULL DEFAULT false,
  joined_at TIMESTAMP NOT NULL DEFAULT now(),
  left_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE message_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  content TEXT,
  blocks JSONB,
  version_number INT NOT NULL,
  edit_reason TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE reactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  emoji VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE files (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE SET NULL,
  uploaded_by UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  file_name VARCHAR NOT NULL,
  file_size INT NOT NULL,
  mime_type VARCHAR NOT NULL,
  storage_url TEXT NOT NULL,
  thumbnail_url TEXT,
  storage_provider VARCHAR NOT NULL DEFAULT 's3',
  checksum VARCHAR,
  is_public BOOLEAN NOT NULL DEFAULT false,
  metadata JSONB DEFAULT '{}',
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE message_files (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  file_id UUID NOT NULL REFERENCES files(id) ON DELETE CASCADE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE message_mentions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  mentioned_user_id UUID REFERENCES users(id) ON DELETE RESTRICT,
  mention_type VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE pinned_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE RESTRICT,
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  pinned_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  name VARCHAR NOT NULL,
  description TEXT,
  resource_type VARCHAR NOT NULL,
  resource_id UUID,
  priority INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE policy_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  policy_id UUID NOT NULL REFERENCES policies(id) ON DELETE RESTRICT,
  subject_type VARCHAR NOT NULL,
  subject_id UUID,
  action VARCHAR NOT NULL,
  effect VARCHAR NOT NULL,
  conditions JSONB DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  message_id UUID REFERENCES messages(id) ON DELETE RESTRICT,
  conversation_id UUID REFERENCES conversations(id) ON DELETE RESTRICT,
  type VARCHAR NOT NULL,
  title VARCHAR,
  body TEXT,
  is_read BOOLEAN NOT NULL DEFAULT false,
  read_at TIMESTAMP,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  type VARCHAR NOT NULL,
  actor_id UUID REFERENCES users(id) ON DELETE RESTRICT,
  resource_type VARCHAR NOT NULL,
  resource_id UUID,
  conversation_id UUID REFERENCES conversations(id) ON DELETE RESTRICT,
  payload JSONB NOT NULL DEFAULT '{}',
  sequence_number INT NOT NULL,
  is_delivered BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  actor_id UUID REFERENCES users(id) ON DELETE RESTRICT,
  action VARCHAR NOT NULL,
  resource_type VARCHAR NOT NULL,
  resource_id UUID,
  before_state JSONB,
  after_state JSONB,
  ip_address VARCHAR,
  user_agent TEXT,
  session_id UUID REFERENCES user_sessions(id) ON DELETE RESTRICT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE message_search_index (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID NOT NULL UNIQUE REFERENCES messages(id) ON DELETE RESTRICT,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE RESTRICT,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  content_plain TEXT,
  content_tsvector TSVECTOR,
  thread_root_id UUID REFERENCES messages(id) ON DELETE RESTRICT,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  message_created_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE sync_cursors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  client_id VARCHAR NOT NULL,
  last_event_sequence INT NOT NULL DEFAULT 0,
  last_synced_at TIMESTAMP NOT NULL DEFAULT now(),
  platform VARCHAR,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE workspace_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  invited_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  email VARCHAR,
  invite_token VARCHAR NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  last_rotated_at TIMESTAMP NOT NULL DEFAULT now(),
  role VARCHAR NOT NULL DEFAULT 'member',
  status VARCHAR NOT NULL DEFAULT 'pending',
  accepted_by UUID REFERENCES users(id) ON DELETE RESTRICT,
  accepted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE user_presence (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  status VARCHAR NOT NULL DEFAULT 'offline',
  status_text VARCHAR,
  status_emoji VARCHAR,
  status_expires_at TIMESTAMP,
  active_client_count INT NOT NULL DEFAULT 0,
  last_active_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE bookmarks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  note TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE webhooks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE SET NULL,
  created_by UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  name VARCHAR NOT NULL,
  target_url TEXT NOT NULL,
  secret_token VARCHAR NOT NULL,
  expires_at TIMESTAMP,
  last_rotated_at TIMESTAMP NOT NULL DEFAULT now(),
  event_types JSONB NOT NULL DEFAULT '[]',
  conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  failure_count INT NOT NULL DEFAULT 0,
  last_triggered_at TIMESTAMP,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE workspace_integrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE SET NULL,
  created_by UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  name VARCHAR NOT NULL,
  type VARCHAR NOT NULL,
  provider VARCHAR NOT NULL,
  access_token TEXT,
  refresh_token TEXT,
  expires_at TIMESTAMP,
  last_rotated_at TIMESTAMP,
  scopes JSONB,
  settings JSONB,
  is_active BOOLEAN NOT NULL DEFAULT true,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE bot_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  integration_id UUID REFERENCES workspace_integrations(id) ON DELETE RESTRICT,
  name VARCHAR NOT NULL,
  api_token TEXT,
  expires_at TIMESTAMP,
  last_rotated_at TIMESTAMP,
  scope JSONB,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE message_reactions_summary (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  emoji VARCHAR NOT NULL,
  count INT NOT NULL DEFAULT 1,
  reacted_user_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE thread_participants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_root_id UUID NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  last_read_at TIMESTAMP,
  is_following BOOLEAN NOT NULL DEFAULT true,
  joined_at TIMESTAMP NOT NULL DEFAULT now(),
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE scheduled_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  content TEXT NOT NULL,
  blocks JSONB,
  scheduled_at TIMESTAMP NOT NULL,
  sent_at TIMESTAMP,
  message_id UUID REFERENCES messages(id) ON DELETE RESTRICT,
  status VARCHAR NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE conversation_tags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  name VARCHAR NOT NULL,
  color VARCHAR,
  description TEXT,
  created_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE conversation_tag_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE RESTRICT,
  tag_id UUID NOT NULL REFERENCES conversation_tags(id) ON DELETE RESTRICT,
  assigned_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE user_notification_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  notify_on_mention BOOLEAN NOT NULL DEFAULT true,
  notify_on_reply BOOLEAN NOT NULL DEFAULT true,
  notify_on_dm BOOLEAN NOT NULL DEFAULT true,
  notify_on_keyword BOOLEAN NOT NULL DEFAULT false,
  keywords JSONB,
  quiet_hours_start VARCHAR,
  quiet_hours_end VARCHAR,
  push_enabled BOOLEAN NOT NULL DEFAULT true,
  email_enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE workflow_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE SET NULL,
  created_by UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  name VARCHAR NOT NULL,
  description TEXT,
  trigger_type VARCHAR NOT NULL,
  trigger_config JSONB NOT NULL,
  steps JSONB NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE workflow_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  template_id UUID NOT NULL REFERENCES workflow_templates(id) ON DELETE RESTRICT,
  triggered_by UUID REFERENCES users(id) ON DELETE RESTRICT,
  trigger_event_id UUID REFERENCES events(id) ON DELETE RESTRICT,
  status VARCHAR NOT NULL DEFAULT 'running',
  input JSONB,
  output JSONB,
  error TEXT,
  started_at TIMESTAMP NOT NULL DEFAULT now(),
  completed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE custom_emojis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE SET NULL,
  created_by UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  name VARCHAR NOT NULL,
  image_url TEXT NOT NULL,
  file_id UUID REFERENCES files(id) ON DELETE SET NULL,
  is_alias BOOLEAN NOT NULL DEFAULT false,
  alias_for VARCHAR,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE channel_sections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  name VARCHAR NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_collapsed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE channel_section_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  section_id UUID NOT NULL REFERENCES channel_sections(id) ON DELETE CASCADE,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE outbox_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  aggregate_type VARCHAR NOT NULL,
  aggregate_id UUID NOT NULL,
  event_type VARCHAR NOT NULL,
  payload JSONB NOT NULL,
  status VARCHAR NOT NULL DEFAULT 'pending',
  retry_count INT NOT NULL DEFAULT 0,
  max_retries INT NOT NULL DEFAULT 5,
  last_error TEXT,
  process_after TIMESTAMP,
  processed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE workspace_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR NOT NULL UNIQUE,
  description TEXT,
  max_members INT,
  max_integrations INT,
  max_storage_gb NUMERIC,
  message_retention_days INT,
  has_audit_logs BOOLEAN NOT NULL DEFAULT false,
  has_advanced_permissions BOOLEAN NOT NULL DEFAULT false,
  has_workflows BOOLEAN NOT NULL DEFAULT false,
  has_guest_access BOOLEAN NOT NULL DEFAULT false,
  price_monthly NUMERIC,
  price_yearly NUMERIC,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE message_link_previews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  url TEXT NOT NULL,
  title VARCHAR,
  description TEXT,
  image_url TEXT,
  site_name VARCHAR,
  favicon_url TEXT,
  is_dismissed BOOLEAN NOT NULL DEFAULT false,
  fetched_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE user_typing_indicators (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  thread_root_id UUID REFERENCES messages(id) ON DELETE RESTRICT,
  started_at TIMESTAMP NOT NULL DEFAULT now(),
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE workspace_billing (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL UNIQUE REFERENCES workspaces(id) ON DELETE RESTRICT,
  plan_id UUID NOT NULL REFERENCES workspace_plans(id) ON DELETE RESTRICT,
  stripe_customer_id VARCHAR,
  stripe_subscription_id VARCHAR,
  billing_email VARCHAR,
  status VARCHAR NOT NULL DEFAULT 'active',
  trial_ends_at TIMESTAMP,
  current_period_start TIMESTAMP,
  current_period_end TIMESTAMP,
  cancelled_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

-- CHECK Constraints
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_email_format') THEN
    ALTER TABLE users ADD CONSTRAINT chk_users_email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_username_format') THEN
    ALTER TABLE users ADD CONSTRAINT chk_users_username_format CHECK (username ~* '^[a-zA-Z0-9_]{3,50}$');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_display_name_length') THEN
    ALTER TABLE users ADD CONSTRAINT chk_users_display_name_length CHECK (char_length(display_name) >= 1 AND char_length(display_name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_avatar_url_format') THEN
    ALTER TABLE users ADD CONSTRAINT chk_users_avatar_url_format CHECK (avatar_url ~* '^https?://');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_bio_length') THEN
    ALTER TABLE users ADD CONSTRAINT chk_users_bio_length CHECK (char_length(bio) <= 10000);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspaces_plan') THEN
    ALTER TABLE workspaces ADD CONSTRAINT chk_workspaces_plan CHECK (plan IN ('free', 'pro', 'business', 'enterprise'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspaces_name_length') THEN
    ALTER TABLE workspaces ADD CONSTRAINT chk_workspaces_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspaces_slug_format') THEN
    ALTER TABLE workspaces ADD CONSTRAINT chk_workspaces_slug_format CHECK (slug ~* '^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(slug) <= 100);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspaces_logo_url_format') THEN
    ALTER TABLE workspaces ADD CONSTRAINT chk_workspaces_logo_url_format CHECK (logo_url ~* '^https?://');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_user_sessions_ip_address_format') THEN
    ALTER TABLE user_sessions ADD CONSTRAINT chk_user_sessions_ip_address_format CHECK (char_length(ip_address) >= 7 AND char_length(ip_address) <= 45);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_memberships_role') THEN
    ALTER TABLE workspace_memberships ADD CONSTRAINT chk_workspace_memberships_role CHECK (role IN ('owner', 'admin', 'member', 'guest', 'bot'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_memberships_status') THEN
    ALTER TABLE workspace_memberships ADD CONSTRAINT chk_workspace_memberships_status CHECK (status IN ('active', 'invited', 'suspended', 'deactivated'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_roles_name_length') THEN
    ALTER TABLE workspace_roles ADD CONSTRAINT chk_workspace_roles_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_roles_description_length') THEN
    ALTER TABLE workspace_roles ADD CONSTRAINT chk_workspace_roles_description_length CHECK (char_length(description) <= 10000);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversations_type') THEN
    ALTER TABLE conversations ADD CONSTRAINT chk_conversations_type CHECK (type IN ('channel', 'dm', 'group_dm', 'thread_channel'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversations_message_count') THEN
    ALTER TABLE conversations ADD CONSTRAINT chk_conversations_message_count CHECK (message_count >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversations_name_length') THEN
    ALTER TABLE conversations ADD CONSTRAINT chk_conversations_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversations_slug_format') THEN
    ALTER TABLE conversations ADD CONSTRAINT chk_conversations_slug_format CHECK (slug ~* '^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(slug) <= 100);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversations_description_length') THEN
    ALTER TABLE conversations ADD CONSTRAINT chk_conversations_description_length CHECK (char_length(description) <= 10000);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_messages_type') THEN
    ALTER TABLE messages ADD CONSTRAINT chk_messages_type CHECK (type IN ('text', 'system', 'file', 'reaction_event', 'slash_command', 'bot', 'ephemeral'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_messages_reply_count') THEN
    ALTER TABLE messages ADD CONSTRAINT chk_messages_reply_count CHECK (reply_count >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_messages_reaction_count') THEN
    ALTER TABLE messages ADD CONSTRAINT chk_messages_reaction_count CHECK (reaction_count >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_messages_no_self_thread') THEN
    ALTER TABLE messages ADD CONSTRAINT chk_messages_no_self_thread CHECK (parent_message_id != id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_messages_content_format') THEN
    ALTER TABLE messages ADD CONSTRAINT chk_messages_content_format CHECK (content_format IN ('markdown', 'plain', 'blocks'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversation_members_role') THEN
    ALTER TABLE conversation_members ADD CONSTRAINT chk_conversation_members_role CHECK (role IN ('owner', 'admin', 'member', 'guest'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversation_members_notification_level') THEN
    ALTER TABLE conversation_members ADD CONSTRAINT chk_conversation_members_notification_level CHECK (notification_level IN ('default', 'all', 'mentions', 'nothing'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_versions_version_number') THEN
    ALTER TABLE message_versions ADD CONSTRAINT chk_message_versions_version_number CHECK (version_number > 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_files_file_size') THEN
    ALTER TABLE files ADD CONSTRAINT chk_files_file_size CHECK (file_size > 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_files_storage_provider') THEN
    ALTER TABLE files ADD CONSTRAINT chk_files_storage_provider CHECK (storage_provider IN ('s3', 'gcs', 'azure', 'local'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_files_file_name_length') THEN
    ALTER TABLE files ADD CONSTRAINT chk_files_file_name_length CHECK (char_length(file_name) >= 1 AND char_length(file_name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_files_mime_type_length') THEN
    ALTER TABLE files ADD CONSTRAINT chk_files_mime_type_length CHECK (char_length(mime_type) >= 1 AND char_length(mime_type) <= 50);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_files_storage_url_format') THEN
    ALTER TABLE files ADD CONSTRAINT chk_files_storage_url_format CHECK (storage_url ~* '^https?://');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_files_thumbnail_url_format') THEN
    ALTER TABLE files ADD CONSTRAINT chk_files_thumbnail_url_format CHECK (thumbnail_url ~* '^https?://');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_files_sort_order') THEN
    ALTER TABLE message_files ADD CONSTRAINT chk_message_files_sort_order CHECK (sort_order >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_mentions_type') THEN
    ALTER TABLE message_mentions ADD CONSTRAINT chk_message_mentions_type CHECK (mention_type IN ('user', 'channel', 'here', 'everyone', 'role'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_policies_resource_type') THEN
    ALTER TABLE policies ADD CONSTRAINT chk_policies_resource_type CHECK (resource_type IN ('workspace', 'conversation', 'message', 'file', 'channel'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_policies_priority') THEN
    ALTER TABLE policies ADD CONSTRAINT chk_policies_priority CHECK (priority >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_policies_name_length') THEN
    ALTER TABLE policies ADD CONSTRAINT chk_policies_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_policies_description_length') THEN
    ALTER TABLE policies ADD CONSTRAINT chk_policies_description_length CHECK (char_length(description) <= 10000);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_policy_rules_subject_type') THEN
    ALTER TABLE policy_rules ADD CONSTRAINT chk_policy_rules_subject_type CHECK (subject_type IN ('user', 'role', 'group', 'everyone'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_policy_rules_effect') THEN
    ALTER TABLE policy_rules ADD CONSTRAINT chk_policy_rules_effect CHECK (effect IN ('allow', 'deny'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_policy_rules_action') THEN
    ALTER TABLE policy_rules ADD CONSTRAINT chk_policy_rules_action CHECK (action IN ('read', 'write', 'delete', 'invite', 'kick', 'pin', 'react', 'upload', 'manage', 'admin'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_notifications_type') THEN
    ALTER TABLE notifications ADD CONSTRAINT chk_notifications_type CHECK (type IN ('mention', 'reply', 'reaction', 'dm', 'channel_invite', 'thread', 'system', 'bot'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_notifications_title_length') THEN
    ALTER TABLE notifications ADD CONSTRAINT chk_notifications_title_length CHECK (char_length(title) >= 1 AND char_length(title) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_events_sequence_number') THEN
    ALTER TABLE events ADD CONSTRAINT chk_events_sequence_number CHECK (sequence_number > 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_events_resource_type_length') THEN
    ALTER TABLE events ADD CONSTRAINT chk_events_resource_type_length CHECK (char_length(resource_type) >= 1 AND char_length(resource_type) <= 50);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_audit_logs_resource_type_length') THEN
    ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_resource_type_length CHECK (char_length(resource_type) >= 1 AND char_length(resource_type) <= 50);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_audit_logs_ip_address_format') THEN
    ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_logs_ip_address_format CHECK (char_length(ip_address) >= 7 AND char_length(ip_address) <= 45);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_sync_cursors_last_event_sequence') THEN
    ALTER TABLE sync_cursors ADD CONSTRAINT chk_sync_cursors_last_event_sequence CHECK (last_event_sequence >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_invites_role') THEN
    ALTER TABLE workspace_invites ADD CONSTRAINT chk_workspace_invites_role CHECK (role IN ('owner', 'admin', 'member', 'guest'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_invites_status') THEN
    ALTER TABLE workspace_invites ADD CONSTRAINT chk_workspace_invites_status CHECK (status IN ('pending', 'accepted', 'expired', 'revoked'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_invites_email_format') THEN
    ALTER TABLE workspace_invites ADD CONSTRAINT chk_workspace_invites_email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_user_presence_status') THEN
    ALTER TABLE user_presence ADD CONSTRAINT chk_user_presence_status CHECK (status IN ('online', 'away', 'dnd', 'offline', 'invisible'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_user_presence_active_client_count') THEN
    ALTER TABLE user_presence ADD CONSTRAINT chk_user_presence_active_client_count CHECK (active_client_count >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_webhooks_failure_count') THEN
    ALTER TABLE webhooks ADD CONSTRAINT chk_webhooks_failure_count CHECK (failure_count >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_webhooks_name_length') THEN
    ALTER TABLE webhooks ADD CONSTRAINT chk_webhooks_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_webhooks_target_url_format') THEN
    ALTER TABLE webhooks ADD CONSTRAINT chk_webhooks_target_url_format CHECK (target_url ~* '^https?://');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_integrations_type') THEN
    ALTER TABLE workspace_integrations ADD CONSTRAINT chk_workspace_integrations_type CHECK (type IN ('oauth', 'webhook', 'bot', 'api_key', 'saml', 'oidc'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_integrations_name_length') THEN
    ALTER TABLE workspace_integrations ADD CONSTRAINT chk_workspace_integrations_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_bot_users_name_length') THEN
    ALTER TABLE bot_users ADD CONSTRAINT chk_bot_users_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_reactions_summary_count') THEN
    ALTER TABLE message_reactions_summary ADD CONSTRAINT chk_message_reactions_summary_count CHECK (count >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_scheduled_messages_status') THEN
    ALTER TABLE scheduled_messages ADD CONSTRAINT chk_scheduled_messages_status CHECK (status IN ('pending', 'sent', 'cancelled', 'failed'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversation_tags_name_length') THEN
    ALTER TABLE conversation_tags ADD CONSTRAINT chk_conversation_tags_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversation_tags_color_format') THEN
    ALTER TABLE conversation_tags ADD CONSTRAINT chk_conversation_tags_color_format CHECK (color ~* '^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_conversation_tags_description_length') THEN
    ALTER TABLE conversation_tags ADD CONSTRAINT chk_conversation_tags_description_length CHECK (char_length(description) <= 10000);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workflow_templates_trigger_type') THEN
    ALTER TABLE workflow_templates ADD CONSTRAINT chk_workflow_templates_trigger_type CHECK (trigger_type IN ('message_posted', 'reaction_added', 'member_joined', 'scheduled', 'manual', 'keyword_match'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workflow_templates_name_length') THEN
    ALTER TABLE workflow_templates ADD CONSTRAINT chk_workflow_templates_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workflow_templates_description_length') THEN
    ALTER TABLE workflow_templates ADD CONSTRAINT chk_workflow_templates_description_length CHECK (char_length(description) <= 10000);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workflow_runs_status') THEN
    ALTER TABLE workflow_runs ADD CONSTRAINT chk_workflow_runs_status CHECK (status IN ('running', 'completed', 'failed', 'cancelled'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_custom_emojis_name_length') THEN
    ALTER TABLE custom_emojis ADD CONSTRAINT chk_custom_emojis_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_custom_emojis_image_url_format') THEN
    ALTER TABLE custom_emojis ADD CONSTRAINT chk_custom_emojis_image_url_format CHECK (image_url ~* '^https?://');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_channel_sections_sort_order') THEN
    ALTER TABLE channel_sections ADD CONSTRAINT chk_channel_sections_sort_order CHECK (sort_order >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_channel_sections_name_length') THEN
    ALTER TABLE channel_sections ADD CONSTRAINT chk_channel_sections_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_channel_section_items_sort_order') THEN
    ALTER TABLE channel_section_items ADD CONSTRAINT chk_channel_section_items_sort_order CHECK (sort_order >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_outbox_events_status') THEN
    ALTER TABLE outbox_events ADD CONSTRAINT chk_outbox_events_status CHECK (status IN ('pending', 'processing', 'delivered', 'failed', 'dead_letter'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_outbox_events_retry_count') THEN
    ALTER TABLE outbox_events ADD CONSTRAINT chk_outbox_events_retry_count CHECK (retry_count >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_outbox_events_max_retries') THEN
    ALTER TABLE outbox_events ADD CONSTRAINT chk_outbox_events_max_retries CHECK (max_retries > 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_outbox_events_aggregate_type_length') THEN
    ALTER TABLE outbox_events ADD CONSTRAINT chk_outbox_events_aggregate_type_length CHECK (char_length(aggregate_type) >= 1 AND char_length(aggregate_type) <= 50);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_outbox_events_event_type_length') THEN
    ALTER TABLE outbox_events ADD CONSTRAINT chk_outbox_events_event_type_length CHECK (char_length(event_type) >= 1 AND char_length(event_type) <= 50);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_plans_price_monthly') THEN
    ALTER TABLE workspace_plans ADD CONSTRAINT chk_workspace_plans_price_monthly CHECK (price_monthly IS NULL OR price_monthly >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_plans_price_yearly') THEN
    ALTER TABLE workspace_plans ADD CONSTRAINT chk_workspace_plans_price_yearly CHECK (price_yearly IS NULL OR price_yearly >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_plans_max_members') THEN
    ALTER TABLE workspace_plans ADD CONSTRAINT chk_workspace_plans_max_members CHECK (max_members IS NULL OR max_members > 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_plans_name_length') THEN
    ALTER TABLE workspace_plans ADD CONSTRAINT chk_workspace_plans_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_plans_description_length') THEN
    ALTER TABLE workspace_plans ADD CONSTRAINT chk_workspace_plans_description_length CHECK (char_length(description) <= 10000);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_plans_message_retention_days_range') THEN
    ALTER TABLE workspace_plans ADD CONSTRAINT chk_workspace_plans_message_retention_days_range CHECK (message_retention_days >= 0);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_link_previews_url_format') THEN
    ALTER TABLE message_link_previews ADD CONSTRAINT chk_message_link_previews_url_format CHECK (url ~* '^https?://');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_link_previews_title_length') THEN
    ALTER TABLE message_link_previews ADD CONSTRAINT chk_message_link_previews_title_length CHECK (char_length(title) >= 1 AND char_length(title) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_link_previews_description_length') THEN
    ALTER TABLE message_link_previews ADD CONSTRAINT chk_message_link_previews_description_length CHECK (char_length(description) <= 10000);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_link_previews_image_url_format') THEN
    ALTER TABLE message_link_previews ADD CONSTRAINT chk_message_link_previews_image_url_format CHECK (image_url ~* '^https?://');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_link_previews_site_name_length') THEN
    ALTER TABLE message_link_previews ADD CONSTRAINT chk_message_link_previews_site_name_length CHECK (char_length(site_name) >= 1 AND char_length(site_name) <= 255);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_message_link_previews_favicon_url_format') THEN
    ALTER TABLE message_link_previews ADD CONSTRAINT chk_message_link_previews_favicon_url_format CHECK (favicon_url ~* '^https?://');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_workspace_billing_status') THEN
    ALTER TABLE workspace_billing ADD CONSTRAINT chk_workspace_billing_status CHECK (status IN ('active', 'trialing', 'past_due', 'cancelled', 'unpaid', 'paused'));
  END IF;
END $$;

-- Indexes
CREATE UNIQUE INDEX idx_users_email ON users(email);
CREATE UNIQUE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_is_bot ON users(is_bot) WHERE deleted_at IS NULL;
CREATE INDEX idx_users_active ON users(deleted_at) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_workspaces_slug ON workspaces(slug);
CREATE INDEX idx_workspaces_owner_id ON workspaces(owner_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_workspaces_is_active ON workspaces(is_active) WHERE is_active = true;
CREATE UNIQUE INDEX idx_user_credentials_user_id ON user_credentials(user_id);
CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE UNIQUE INDEX idx_user_sessions_token ON user_sessions(session_token);
CREATE INDEX idx_user_sessions_active ON user_sessions(user_id, is_active) WHERE is_active = true;
CREATE INDEX idx_workspace_memberships_workspace_id ON workspace_memberships(workspace_id);
CREATE INDEX idx_workspace_memberships_user_id ON workspace_memberships(user_id);
CREATE UNIQUE INDEX idx_workspace_memberships_workspace_user ON workspace_memberships(workspace_id, user_id);
CREATE INDEX idx_workspace_memberships_active ON workspace_memberships(workspace_id, status) WHERE status = 'active';
CREATE INDEX idx_workspace_memberships_invited_by ON workspace_memberships(invited_by);
CREATE INDEX idx_workspace_roles_workspace_id ON workspace_roles(workspace_id);
CREATE UNIQUE INDEX idx_workspace_roles_workspace_name ON workspace_roles(workspace_id, name);
CREATE INDEX idx_conversations_workspace_id ON conversations(workspace_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_conversations_created_by ON conversations(created_by) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_conversations_workspace_slug ON conversations(workspace_id, slug) WHERE slug IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_conversations_workspace_type ON conversations(workspace_id, type) WHERE deleted_at IS NULL;
CREATE INDEX idx_conversations_last_message_at ON conversations(workspace_id, last_message_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_conversations_active ON conversations(workspace_id, is_archived) WHERE is_archived = false AND deleted_at IS NULL;
CREATE INDEX idx_messages_conversation_id ON messages(conversation_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_messages_user_id ON messages(user_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_messages_workspace_id ON messages(workspace_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_messages_parent_message_id ON messages(parent_message_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_messages_thread_root_id ON messages(thread_root_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_messages_conversation_created ON messages(conversation_id, created_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_messages_threads ON messages(conversation_id, parent_message_id, created_at) WHERE parent_message_id IS NOT NULL;
CREATE INDEX idx_messages_pinned ON messages(conversation_id, is_pinned) WHERE is_pinned = true;
CREATE INDEX idx_conversation_members_conversation_id ON conversation_members(conversation_id);
CREATE INDEX idx_conversation_members_user_id ON conversation_members(user_id);
CREATE UNIQUE INDEX idx_conversation_members_conv_user ON conversation_members(conversation_id, user_id);
CREATE INDEX idx_conversation_members_last_read ON conversation_members(conversation_id, last_read_at);
CREATE INDEX idx_conversation_members_last_read_message_id ON conversation_members(last_read_message_id);
CREATE INDEX idx_message_versions_message_id ON message_versions(message_id);
CREATE UNIQUE INDEX idx_message_versions_message_version ON message_versions(message_id, version_number);
CREATE INDEX idx_message_versions_user_id ON message_versions(user_id);
CREATE INDEX idx_reactions_message_id ON reactions(message_id);
CREATE INDEX idx_reactions_user_id ON reactions(user_id);
CREATE UNIQUE INDEX idx_reactions_message_user_emoji ON reactions(message_id, user_id, emoji);
CREATE INDEX idx_reactions_workspace_id ON reactions(workspace_id);
CREATE INDEX idx_files_workspace_id ON files(workspace_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_files_uploaded_by ON files(uploaded_by) WHERE deleted_at IS NULL;
CREATE INDEX idx_files_mime_type ON files(mime_type) WHERE deleted_at IS NULL;
CREATE INDEX idx_files_active ON files(workspace_id, uploaded_by) WHERE deleted_at IS NULL;
CREATE INDEX idx_message_files_message_id ON message_files(message_id);
CREATE INDEX idx_message_files_file_id ON message_files(file_id);
CREATE UNIQUE INDEX idx_message_files_message_file ON message_files(message_id, file_id);
CREATE INDEX idx_message_mentions_message_id ON message_mentions(message_id);
CREATE INDEX idx_message_mentions_mentioned_user_id ON message_mentions(mentioned_user_id);
CREATE INDEX idx_message_mentions_workspace_id ON message_mentions(workspace_id);
CREATE INDEX idx_pinned_messages_conversation_id ON pinned_messages(conversation_id);
CREATE INDEX idx_pinned_messages_message_id ON pinned_messages(message_id);
CREATE UNIQUE INDEX idx_pinned_messages_conv_msg ON pinned_messages(conversation_id, message_id);
CREATE INDEX idx_pinned_messages_pinned_by ON pinned_messages(pinned_by);
CREATE INDEX idx_pinned_messages_workspace_id ON pinned_messages(workspace_id);
CREATE INDEX idx_policies_workspace_id ON policies(workspace_id);
CREATE INDEX idx_policies_resource ON policies(resource_type, resource_id);
CREATE INDEX idx_policies_active ON policies(workspace_id, is_active) WHERE is_active = true;
CREATE INDEX idx_policy_rules_policy_id ON policy_rules(policy_id);
CREATE INDEX idx_policy_rules_subject ON policy_rules(subject_type, subject_id);
CREATE INDEX idx_policy_rules_action ON policy_rules(action, effect);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_workspace_id ON notifications(workspace_id);
CREATE INDEX idx_notifications_message_id ON notifications(message_id);
CREATE INDEX idx_notifications_unread ON notifications(user_id, is_read, created_at) WHERE is_read = false;
CREATE INDEX idx_notifications_conversation_id ON notifications(conversation_id);
CREATE INDEX idx_events_workspace_id ON events(workspace_id);
CREATE INDEX idx_events_actor_id ON events(actor_id);
CREATE INDEX idx_events_resource ON events(resource_type, resource_id);
CREATE INDEX idx_events_conversation_id ON events(conversation_id);
CREATE UNIQUE INDEX idx_events_workspace_seq ON events(workspace_id, sequence_number);
CREATE INDEX idx_events_type_created ON events(workspace_id, type, created_at);
CREATE INDEX idx_events_undelivered ON events(workspace_id, is_delivered, created_at) WHERE is_delivered = false;
CREATE INDEX idx_audit_logs_workspace_id ON audit_logs(workspace_id);
CREATE INDEX idx_audit_logs_actor_id ON audit_logs(actor_id);
CREATE INDEX idx_audit_logs_resource ON audit_logs(resource_type, resource_id);
CREATE INDEX idx_audit_logs_action ON audit_logs(workspace_id, action, created_at);
CREATE INDEX idx_audit_logs_session_id ON audit_logs(session_id);
CREATE INDEX idx_message_search_workspace_id ON message_search_index(workspace_id);
CREATE INDEX idx_message_search_conversation_id ON message_search_index(conversation_id);
CREATE INDEX idx_message_search_user_id ON message_search_index(user_id);
CREATE INDEX idx_message_search_tsvector ON message_search_index(content_tsvector);
CREATE INDEX idx_message_search_thread_root_id ON message_search_index(thread_root_id);
CREATE INDEX idx_message_search_active ON message_search_index(workspace_id, conversation_id, message_created_at) WHERE is_deleted = false;
CREATE INDEX idx_message_search_index_message_id ON message_search_index(message_id);
CREATE INDEX idx_sync_cursors_workspace_user ON sync_cursors(workspace_id, user_id);
CREATE UNIQUE INDEX idx_sync_cursors_client ON sync_cursors(workspace_id, user_id, client_id);
CREATE INDEX idx_workspace_invites_workspace_id ON workspace_invites(workspace_id);
CREATE UNIQUE INDEX idx_workspace_invites_token ON workspace_invites(invite_token);
CREATE INDEX idx_workspace_invites_email ON workspace_invites(workspace_id, email);
CREATE INDEX idx_workspace_invites_pending ON workspace_invites(workspace_id, status) WHERE status = 'pending';
CREATE INDEX idx_workspace_invites_invited_by ON workspace_invites(invited_by);
CREATE INDEX idx_workspace_invites_accepted_by ON workspace_invites(accepted_by);
CREATE INDEX idx_user_presence_user_id ON user_presence(user_id);
CREATE UNIQUE INDEX idx_user_presence_workspace_user ON user_presence(workspace_id, user_id);
CREATE INDEX idx_user_presence_online ON user_presence(workspace_id, status) WHERE status IN ('online','away','dnd');
CREATE INDEX idx_bookmarks_user_id ON bookmarks(user_id);
CREATE INDEX idx_bookmarks_workspace_id ON bookmarks(workspace_id);
CREATE INDEX idx_bookmarks_message_id ON bookmarks(message_id);
CREATE UNIQUE INDEX idx_bookmarks_user_message ON bookmarks(user_id, message_id);
CREATE INDEX idx_webhooks_workspace_id ON webhooks(workspace_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_webhooks_created_by ON webhooks(created_by) WHERE deleted_at IS NULL;
CREATE INDEX idx_webhooks_active ON webhooks(workspace_id, is_active) WHERE is_active = true AND deleted_at IS NULL;
CREATE INDEX idx_webhooks_conversation_id ON webhooks(conversation_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_workspace_integrations_workspace_id ON workspace_integrations(workspace_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_workspace_integrations_type ON workspace_integrations(type) WHERE deleted_at IS NULL;
CREATE INDEX idx_workspace_integrations_active ON workspace_integrations(workspace_id, is_active) WHERE is_active = true AND deleted_at IS NULL;
CREATE INDEX idx_workspace_integrations_created_by ON workspace_integrations(created_by) WHERE deleted_at IS NULL;
CREATE INDEX idx_bot_users_user_id ON bot_users(user_id);
CREATE INDEX idx_bot_users_workspace_id ON bot_users(workspace_id);
CREATE INDEX idx_bot_users_integration_id ON bot_users(integration_id);
CREATE INDEX idx_message_reactions_summary_message_id ON message_reactions_summary(message_id);
CREATE UNIQUE INDEX idx_message_reactions_summary_unique ON message_reactions_summary(message_id, emoji);
CREATE INDEX idx_message_reactions_summary_workspace_id ON message_reactions_summary(workspace_id);
CREATE INDEX idx_thread_participants_thread_root_id ON thread_participants(thread_root_id);
CREATE INDEX idx_thread_participants_user_id ON thread_participants(user_id);
CREATE UNIQUE INDEX idx_thread_participants_unique ON thread_participants(thread_root_id, user_id);
CREATE INDEX idx_thread_participants_following ON thread_participants(user_id, is_following) WHERE is_following = true;
CREATE INDEX idx_thread_participants_workspace_id ON thread_participants(workspace_id);
CREATE INDEX idx_scheduled_messages_workspace_id ON scheduled_messages(workspace_id);
CREATE INDEX idx_scheduled_messages_user_id ON scheduled_messages(user_id);
CREATE INDEX idx_scheduled_messages_scheduled_at ON scheduled_messages(scheduled_at);
CREATE INDEX idx_scheduled_messages_pending ON scheduled_messages(scheduled_at, status) WHERE status = 'pending';
CREATE INDEX idx_scheduled_messages_conversation_id ON scheduled_messages(conversation_id);
CREATE INDEX idx_scheduled_messages_message_id ON scheduled_messages(message_id);
CREATE INDEX idx_conversation_tags_workspace_id ON conversation_tags(workspace_id);
CREATE UNIQUE INDEX idx_conversation_tags_unique_name ON conversation_tags(workspace_id, name);
CREATE INDEX idx_conversation_tags_created_by ON conversation_tags(created_by);
CREATE INDEX idx_conversation_tag_assignments_conversation_id ON conversation_tag_assignments(conversation_id);
CREATE INDEX idx_conversation_tag_assignments_tag_id ON conversation_tag_assignments(tag_id);
CREATE UNIQUE INDEX idx_conversation_tag_assignments_unique ON conversation_tag_assignments(conversation_id, tag_id);
CREATE INDEX idx_conversation_tag_assignments_assigned_by ON conversation_tag_assignments(assigned_by);
CREATE INDEX idx_user_notification_preferences_user_id ON user_notification_preferences(user_id);
CREATE UNIQUE INDEX idx_user_notification_preferences_unique ON user_notification_preferences(user_id, workspace_id);
CREATE INDEX idx_workflow_templates_workspace_id ON workflow_templates(workspace_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_workflow_templates_active ON workflow_templates(workspace_id, is_active) WHERE is_active = true AND deleted_at IS NULL;
CREATE INDEX idx_workflow_templates_created_by ON workflow_templates(created_by) WHERE deleted_at IS NULL;
CREATE INDEX idx_workflow_runs_workspace_id ON workflow_runs(workspace_id);
CREATE INDEX idx_workflow_runs_template_id ON workflow_runs(template_id);
CREATE INDEX idx_workflow_runs_status ON workflow_runs(status, started_at);
CREATE INDEX idx_workflow_runs_triggered_by ON workflow_runs(triggered_by);
CREATE INDEX idx_workflow_runs_trigger_event_id ON workflow_runs(trigger_event_id);
CREATE INDEX idx_custom_emojis_workspace_id ON custom_emojis(workspace_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_custom_emojis_unique_name ON custom_emojis(workspace_id, name) WHERE deleted_at IS NULL;
CREATE INDEX idx_custom_emojis_created_by ON custom_emojis(created_by) WHERE deleted_at IS NULL;
CREATE INDEX idx_custom_emojis_file_id ON custom_emojis(file_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_channel_sections_user_workspace ON channel_sections(user_id, workspace_id);
CREATE INDEX idx_channel_section_items_section_id ON channel_section_items(section_id);
CREATE UNIQUE INDEX idx_channel_section_items_unique ON channel_section_items(section_id, conversation_id);
CREATE INDEX idx_outbox_events_status ON outbox_events(status, process_after) WHERE status = 'pending';
CREATE INDEX idx_outbox_events_workspace_id ON outbox_events(workspace_id);
CREATE INDEX idx_outbox_events_aggregate ON outbox_events(aggregate_type, aggregate_id);
CREATE UNIQUE INDEX idx_workspace_plans_name ON workspace_plans(name);
CREATE INDEX idx_workspace_plans_active ON workspace_plans(is_active) WHERE is_active = true;
CREATE INDEX idx_message_link_previews_message_id ON message_link_previews(message_id);
CREATE INDEX idx_message_link_previews_workspace_id ON message_link_previews(workspace_id);
CREATE INDEX idx_user_typing_indicators_conversation_id ON user_typing_indicators(conversation_id, expires_at);
CREATE UNIQUE INDEX idx_user_typing_indicators_unique ON user_typing_indicators(conversation_id, user_id);
CREATE INDEX idx_user_typing_indicators_workspace_id ON user_typing_indicators(workspace_id);
CREATE INDEX idx_user_typing_indicators_thread_root_id ON user_typing_indicators(thread_root_id);
CREATE UNIQUE INDEX idx_workspace_billing_workspace_id ON workspace_billing(workspace_id);
CREATE INDEX idx_workspace_billing_stripe_customer ON workspace_billing(stripe_customer_id);
CREATE INDEX idx_workspace_billing_stripe_subscription ON workspace_billing(stripe_subscription_id);
CREATE INDEX idx_workspace_billing_plan_id ON workspace_billing(plan_id);

-- Polymorphic Relationships
-- The following tables use polymorphic associations where a type column
-- discriminates which parent table the ID column references.
-- policies: resource_id + resource_type (prefix: resource)
-- policy_rules: subject_id + subject_type (prefix: subject)
-- events: resource_id + resource_type (prefix: resource)
-- audit_logs: resource_id + resource_type (prefix: resource)
-- outbox_events: aggregate_id + aggregate_type (prefix: aggregate)

CREATE INDEX idx_policies_resource_poly ON policies(resource_type, resource_id);
CREATE INDEX idx_policy_rules_subject_poly ON policy_rules(subject_type, subject_id);
CREATE INDEX idx_events_resource_poly ON events(resource_type, resource_id);
CREATE INDEX idx_audit_logs_resource_poly ON audit_logs(resource_type, resource_id);
CREATE INDEX idx_outbox_events_aggregate_poly ON outbox_events(aggregate_type, aggregate_id);

